### ISSUE TITLE
Some CEM are supported in latest Optifine

### ISSUE THREAD

**Issue by GeForceLegend** [ewanhowell5195/cemTemplateModels#1]
Armadillo, bogged (including outer), creaking, wind charge and wolf armor are now supported in OptiFine 1.21.3_HD_U_J2_pre5.
Creaking also contains creaking_transient but it will fallback to creaking. Considering it will be removed in next release, there might be no need to add it.

**Comment by ewanhowell5195** [comment]
i am aware
